name: Trivy Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # ← REQUIRED "uses" key

      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .  # ← REQUIRED "run" key

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master  # ← REQUIRED "uses" key
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
