name: Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (multi-stage)
        run: docker build -t trivy-demo:${{ github.sha }} .

      - name: Scan final image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'trivy-demo:${{ github.sha }}'
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
          output: 'trivy-results.sarif'
          scanners: 'vuln'  # Focus only on vulnerabilities

      # Optional: Scan the builder stage for development dependencies
      - name: Scan builder stage (optional)
        if: ${{ always() }}  # Run even if previous
